'spurious-sqs':
  :image: 'smaj/spurious-sqs'

'spurious-s3':
  :image: 'smaj/spurious-s3'

'spurious-dynamo':
  :image: 'smaj/spurious-dynamo'

'spurious-memcached':
  :image: 'smaj/memcached'

'spurious-elasticache':
  :image: 'smaj/fake-elasticache'
  :link:
    - 'spurious-memcached:memcached01'
  :env:
    FAKEELASTICACHE_DEFAULT_HOST: '127.0.0.1'

'spurious-elasticache-docker':
  :image: 'smaj/fake-elasticache'
  :link:
    - 'spurious-memcached:memcached01'
